# Generated by Django 5.1.7 on 2025-04-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
