# Generated by Django 5.1.7 on 2025-04-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sensordata_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='bluetooth_mac',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
